name: offline_sync

packages:
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true
  version:
    message: "chore: version packages"

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Run the analyzer for all packages

  test:
    run: melos exec -- flutter test
    description: Run tests for every package that contains a test directory
    packageFilters:
      dirExists: test

  format:
    run: melos exec -- dart format . --set-exit-if-changed
    description: Check code formatting across all packages

  format:fix:
    run: melos exec -- dart format .
    description: Automatically fix code formatting
